### ISSUE TITLE
Visualization of Weight Loss Landscape

### ISSUE THREAD

**Issue by shudong-zhang** [csdongxian/AWP#3]
Is there a code for "Visualization of Weight Loss Landscape"?

**Comment by csdongxian** [comment]
Hello, this repository does not contain any code for visualization.

Actually, we adopt codes from [https://github.com/tomgoldstein/loss-landscape](https://github.com/tomgoldstein/loss-landscape) to visualize the weight loss landscape of adversarially trained model. In particular, based on [evaluation.py](https://github.com/tomgoldstein/loss-landscape/blob/master/evaluation.py), we reimplement an adv_evaluation.py to calculate the test robust accuracy under the PGD attack.

Hope this will help you :)
